var hero_dict = [
  {'ID': 102, 'key': 'npc_dota_hero_abaddon', 'name': 'Abaddon'},
  {'ID': 73, 'key': 'npc_dota_hero_alchemist', 'name': 'Alchemist'},
  {'ID': 68, 'key': 'npc_dota_hero_ancient_apparition', 'name': 'Ancient Apparition'},
  {'ID': 1, 'key': 'npc_dota_hero_antimage', 'name': 'Anti-Mage'},
  {'ID': 2, 'key': 'npc_dota_hero_axe', 'name': 'Axe'},
  {'ID': 3, 'key': 'npc_dota_hero_bane', 'name': 'Bane'},
  {'ID': 65, 'key': 'npc_dota_hero_batrider', 'name': 'Batrider'},
  {'ID': 38, 'key': 'npc_dota_hero_beastmaster', 'name': 'Beastmaster'},
  {'ID': 4, 'key': 'npc_dota_hero_bloodseeker', 'name': 'Bloodseeker'},
  {'ID': 62, 'key': 'npc_dota_hero_bounty_hunter', 'name': 'Bounty Hunter'},
  {'ID': 78, 'key': 'npc_dota_hero_brewmaster', 'name': 'Brewmaster'},
  {'ID': 99, 'key': 'npc_dota_hero_bristleback', 'name': 'Bristleback'},
  {'ID': 61, 'key': 'npc_dota_hero_broodmother', 'name': 'Broodmother'},
  {'ID': 96, 'key': 'npc_dota_hero_centaur', 'name': 'Centaur Warrunner'},
  {'ID': 81, 'key': 'npc_dota_hero_chaos_knight', 'name': 'Chaos Knight'},
  {'ID': 66, 'key': 'npc_dota_hero_chen', 'name': 'Chen'},
  {'ID': 56, 'key': 'npc_dota_hero_clinkz', 'name': 'Clinkz'},
  {'ID': 5, 'key': 'npc_dota_hero_crystal_maiden', 'name': 'Crystal Maiden'},
  {'ID': 55, 'key': 'npc_dota_hero_dark_seer', 'name': 'Dark Seer'},
  {'ID': 50, 'key': 'npc_dota_hero_dazzle', 'name': 'Dazzle'},
  {'ID': 43, 'key': 'npc_dota_hero_death_prophet', 'name': 'Death Prophet'},
  {'ID': 87, 'key': 'npc_dota_hero_disruptor', 'name': 'Disruptor'},
  {'ID': 69, 'key': 'npc_dota_hero_doom_bringer', 'name': 'Doom'},
  {'ID': 49, 'key': 'npc_dota_hero_dragon_knight', 'name': 'Dragon Knight'},
  {'ID': 6, 'key': 'npc_dota_hero_drow_ranger', 'name': 'Drow Ranger'},
  {'ID': 107, 'key': 'npc_dota_hero_earth_spirit', 'name': 'Earth Spirit'},
  {'ID': 7, 'key': 'npc_dota_hero_earthshaker', 'name': 'Earthshaker'},
  {'ID': 103, 'key': 'npc_dota_hero_elder_titan', 'name': 'Elder Titan'},
  {'ID': 106, 'key': 'npc_dota_hero_ember_spirit', 'name': 'Ember Spirit'},
  {'ID': 58, 'key': 'npc_dota_hero_enchantress', 'name': 'Enchantress'},
  {'ID': 33, 'key': 'npc_dota_hero_enigma', 'name': 'Enigma'},
  {'ID': 41, 'key': 'npc_dota_hero_faceless_void', 'name': 'Faceless Void'},
  {'ID': 53, 'key': 'npc_dota_hero_furion', 'name': 'Nature\'s Prophet'},
  {'ID': 72, 'key': 'npc_dota_hero_gyrocopter', 'name': 'Gyrocopter'},
  {'ID': 59, 'key': 'npc_dota_hero_huskar', 'name': 'Huskar'},
  {'ID': 74, 'key': 'npc_dota_hero_invoker', 'name': 'Invoker'},
  {'ID': 64, 'key': 'npc_dota_hero_jakiro', 'name': 'Jakiro'},
  {'ID': 8, 'key': 'npc_dota_hero_juggernaut', 'name': 'Juggernaut'},
  {'ID': 90, 'key': 'npc_dota_hero_keeper_of_the_light', 'name': 'Keeper of the Light'},
  {'ID': 23, 'key': 'npc_dota_hero_kunkka', 'name': 'Kunkka'},
  {'ID': 104, 'key': 'npc_dota_hero_legion_commander', 'name': 'Legion Commander'},
  {'ID': 52, 'key': 'npc_dota_hero_leshrac', 'name': 'Leshrac'},
  {'ID': 31, 'key': 'npc_dota_hero_lich', 'name': 'Lich'},
  {'ID': 54, 'key': 'npc_dota_hero_life_stealer', 'name': 'Lifestealer'},
  {'ID': 25, 'key': 'npc_dota_hero_lina', 'name': 'Lina'},
  {'ID': 26, 'key': 'npc_dota_hero_lion', 'name': 'Lion'},
  {'ID': 80, 'key': 'npc_dota_hero_lone_druid', 'name': 'Lone Druid'},
  {'ID': 48, 'key': 'npc_dota_hero_luna', 'name': 'Luna'},
  {'ID': 77, 'key': 'npc_dota_hero_lycan', 'name': 'Lycan'},
  {'ID': 97, 'key': 'npc_dota_hero_magnataur', 'name': 'Magnus'},
  {'ID': 94, 'key': 'npc_dota_hero_medusa', 'name': 'Medusa'},
  {'ID': 82, 'key': 'npc_dota_hero_meepo', 'name': 'Meepo'},
  {'ID': 9, 'key': 'npc_dota_hero_mirana', 'name': 'Mirana'},
  {'ID': 10, 'key': 'npc_dota_hero_morphling', 'name': 'Morphling'},
  {'ID': 89, 'key': 'npc_dota_hero_naga_siren', 'name': 'Naga Siren'},
  {'ID': 36, 'key': 'npc_dota_hero_necrolyte', 'name': 'Necrophos'},
  {'ID': 11, 'key': 'npc_dota_hero_nevermore', 'name': 'Shadow Fiend'},
  {'ID': 60, 'key': 'npc_dota_hero_night_stalker', 'name': 'Night Stalker'},
  {'ID': 88, 'key': 'npc_dota_hero_nyx_assassin', 'name': 'Nyx Assassin'},
  {'ID': 76, 'key': 'npc_dota_hero_obsidian_destroyer', 'name': 'Outworld Devourer'},
  {'ID': 84, 'key': 'npc_dota_hero_ogre_magi', 'name': 'Ogre Magi'},
  {'ID': 57, 'key': 'npc_dota_hero_omniknight', 'name': 'Omniknight'},
  {'ID': 111, 'key': 'npc_dota_hero_oracle', 'name': 'Oracle'},
  {'ID': 44, 'key': 'npc_dota_hero_phantom_assassin', 'name': 'Phantom Assassin'},
  {'ID': 12, 'key': 'npc_dota_hero_phantom_lancer', 'name': 'Phantom Lancer'},
  {'ID': 110, 'key': 'npc_dota_hero_phoenix', 'name': 'Phoenix'},
  {'ID': 13, 'key': 'npc_dota_hero_puck', 'name': 'Puck'},
  {'ID': 14, 'key': 'npc_dota_hero_pudge', 'name': 'Pudge'},
  {'ID': 45, 'key': 'npc_dota_hero_pugna', 'name': 'Pugna'},
  {'ID': 39, 'key': 'npc_dota_hero_queenofpain', 'name': 'Queen of Pain'},
  {'ID': 51, 'key': 'npc_dota_hero_rattletrap', 'name': 'Clockwerk'},
  {'ID': 15, 'key': 'npc_dota_hero_razor', 'name': 'Razor'},
  {'ID': 32, 'key': 'npc_dota_hero_riki', 'name': 'Riki'},
  {'ID': 86, 'key': 'npc_dota_hero_rubick', 'name': 'Rubick'},
  {'ID': 16, 'key': 'npc_dota_hero_sand_king', 'name': 'Sand King'},
  {'ID': 79, 'key': 'npc_dota_hero_shadow_demon', 'name': 'Shadow Demon'},
  {'ID': 27, 'key': 'npc_dota_hero_shadow_shaman', 'name': 'Shadow Shaman'},
  {'ID': 98, 'key': 'npc_dota_hero_shredder', 'name': 'Timbersaw'},
  {'ID': 75, 'key': 'npc_dota_hero_silencer', 'name': 'Silencer'},
  {'ID': 42, 'key': 'npc_dota_hero_skeleton_king', 'name': 'Wraith King'},
  {'ID': 101, 'key': 'npc_dota_hero_skywrath_mage', 'name': 'Skywrath Mage'},
  {'ID': 28, 'key': 'npc_dota_hero_slardar', 'name': 'Slardar'},
  {'ID': 93, 'key': 'npc_dota_hero_slark', 'name': 'Slark'},
  {'ID': 35, 'key': 'npc_dota_hero_sniper', 'name': 'Sniper'},
  {'ID': 67, 'key': 'npc_dota_hero_spectre', 'name': 'Spectre'},
  {'ID': 71, 'key': 'npc_dota_hero_spirit_breaker', 'name': 'Spirit Breaker'},
  {'ID': 17, 'key': 'npc_dota_hero_storm_spirit', 'name': 'Storm Spirit'},
  {'ID': 18, 'key': 'npc_dota_hero_sven', 'name': 'Sven'},
  {'ID': 105, 'key': 'npc_dota_hero_techies', 'name': 'Techies'},
  {'ID': 46, 'key': 'npc_dota_hero_templar_assassin', 'name': 'Templar Assassin'},
  {'ID': 109, 'key': 'npc_dota_hero_terrorblade', 'name': 'Terrorblade'},
  {'ID': 29, 'key': 'npc_dota_hero_tidehunter', 'name': 'Tidehunter'},
  {'ID': 34, 'key': 'npc_dota_hero_tinker', 'name': 'Tinker'},
  {'ID': 19, 'key': 'npc_dota_hero_tiny', 'name': 'Tiny'},
  {'ID': 83, 'key': 'npc_dota_hero_treant', 'name': 'Treant Protector'},
  {'ID': 95, 'key': 'npc_dota_hero_troll_warlord', 'name': 'Troll Warlord'},
  {'ID': 100, 'key': 'npc_dota_hero_tusk', 'name': 'Tusk'},
  {'ID': 85, 'key': 'npc_dota_hero_undying', 'name': 'Undying'},
  {'ID': 70, 'key': 'npc_dota_hero_ursa', 'name': 'Ursa'},
  {'ID': 20, 'key': 'npc_dota_hero_vengefulspirit', 'name': 'Vengeful Spirit'},
  {'ID': 40, 'key': 'npc_dota_hero_venomancer', 'name': 'Venomancer'},
  {'ID': 47, 'key': 'npc_dota_hero_viper', 'name': 'Viper'},
  {'ID': 92, 'key': 'npc_dota_hero_visage', 'name': 'Visage'},
  {'ID': 37, 'key': 'npc_dota_hero_warlock', 'name': 'Warlock'},
  {'ID': 63, 'key': 'npc_dota_hero_weaver', 'name': 'Weaver'},
  {'ID': 21, 'key': 'npc_dota_hero_windrunner', 'name': 'Windranger'},
  {'ID': 112, 'key': 'npc_dota_hero_winter_wyvern', 'name': 'Winter Wyvern'},
  {'ID': 91, 'key': 'npc_dota_hero_wisp', 'name': 'Io'},
  {'ID': 30, 'key': 'npc_dota_hero_witch_doctor', 'name': 'Witch Doctor'},
  {'ID': 22, 'key': 'npc_dota_hero_zuus', 'name': 'Zeus'},
  {'ID': 113, 'key': 'npc_dota_hero_arc_warden', 'name': 'Arc Warden'},
  {'ID': 108, 'key': 'npc_dota_hero_abyssal_underlord', 'name': 'Abyssal Underlord'}
];

var getHeroByID = function(id){
  var hero = hero_dict.find(function(hero){return hero.ID === id;});
  if (hero === undefined){
    throw "No hero with ID: " + id;
  } else {
    return hero;
  }
};

module.exports = {
  "getHeroByID": getHeroByID,
  "raw": hero_dict
};
